url: http://www.bradcoffield.com
baseurl: /APIs-for-librarians
exclude: ['readme.md', 'license']
title: 'APIs for Librarians'
author: 'Brad Coffield'
githuburl: 'https://github.com/BradCoffield'
twitterurl: 'https://twitter.com/BradCoffield'
personalhomepage: 'http://www.bradcoffield.com'
<<<<<<< Updated upstream
markdown: kramdown
=======
#markdown: kramdown
highlighter: Pygments
>>>>>>> Stashed changes
permalink: /:title.html
collections:
  libguides:   
    output: true
  libcal:
    output: true
  libanswers:
    output: true

        
